# Generated by Django 5.2 on 2025-04-10 07:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='full name')),
                ('age', models.PositiveIntegerField(verbose_name='age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='gender')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID number')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'passenger',
                'verbose_name_plural': 'passengers',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100, verbose_name='origin city')),
                ('destination', models.CharField(max_length=100, verbose_name='destination city')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='distance (km)')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='estimated journey time')),
            ],
            options={
                'verbose_name': 'route',
                'verbose_name_plural': 'routes',
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True, verbose_name='bus number')),
                ('departure_time', models.DateTimeField(verbose_name='departure time')),
                ('arrival_time', models.DateTimeField(verbose_name='arrival time')),
                ('total_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='total seats')),
                ('available_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='available seats')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='fare')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='booking.route')),
            ],
            options={
                'verbose_name': 'bus',
                'verbose_name_plural': 'buses',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='booking time')),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='BOOKED', max_length=20, verbose_name='status')),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total fare')),
                ('seat_numbers', models.CharField(help_text='Comma-separated seat numbers', max_length=255, verbose_name='seat numbers')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='booking.bus')),
                ('passengers', models.ManyToManyField(related_name='tickets', to='booking.passenger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['-booking_time'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund')], max_length=20, verbose_name='transaction type')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('related_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='booking.ticket')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='booking.wallet')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
