# Generated by Django 5.2 on 2025-04-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='has_general_seats',
            field=models.BooleanField(default=True, verbose_name='has general seats'),
        ),
        migrations.AddField(
            model_name='bus',
            name='has_luxury_seats',
            field=models.BooleanField(default=False, verbose_name='has luxury seats'),
        ),
        migrations.AddField(
            model_name='bus',
            name='has_sleeper_seats',
            field=models.BooleanField(default=False, verbose_name='has sleeper seats'),
        ),
        migrations.AddField(
            model_name='bus',
            name='luxury_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='luxury fare'),
        ),
        migrations.AddField(
            model_name='bus',
            name='sleeper_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sleeper fare'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_class',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SLEEPER', 'Sleeper'), ('LUXURY', 'Luxury')], default='GENERAL', max_length=20, verbose_name='seat class'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='fare',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base fare'),
        ),
    ]
