# Generated by Django 5.2 on 2025-04-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_multistopbus_id_alter_multistoproute_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='end_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arriving_tickets', to='booking.routestop'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departing_tickets', to='booking.routestop'),
        ),
    ]
